### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Climax-Arc** [AndyRusso/untoggle-sprint#1] opened 2024-05-25 14:16 UTC
mods used: untoggle-sprint with optifine, optifabric, fabric api, minecracft version 1.20.1

[here](https://mclo.gs/YZswiMz) are logs hopefully they help.

how to recreate this crash?
1. Use mods mentioned above
2. launch game

**Comment by AndyRusso** [comment] 2024-05-26 08:56
Hello! This is a very well made report, thank you, the logs were helpful.

Optifine / Optifabric are known to break compatibility with other mods. The issue in question is caused by the technical way that I change the button `Spring: Hold` to `Spring: Untoggle` in the Minecraft settings (see [Modrinth gallery](https://modrinth.com/mod/untoggle-sprint/gallery)).
Unfortunately I do not see a way to solve this on my side without undesired side effects. But since that feature is not essential to the mod's functionality, I made a build of it for you that just doesn't try to change that. You can download it [in this GitHub Release](https://github.com/AndyRusso/untoggle-sprint/releases/tag/optifine-compat) in this repository. Make sure you have sprint set to `Sprint: Hold` to enable the mod.

Closing this as not planned because of aforementioned reasons.

**Closed as not planned by AndyRusso** 2024-05-26 08:56 UTC

**Comment by AndyRusso** [comment] 2024-05-26 10:07
Hello. Optifine / Optifabric is known to break compatibility between mods, and now including Untoggle sprint. There is nothing I can do, and I recommend not using Optifine / Optifabric if possible.
